### ISSUE TITLE
 Сannot import name 'read_plink1_bin' from 'pandas_plink'

### ISSUE THREAD

**Issue by kamilla0503** [limix/pandas-plink#11]
I have installed via pip pandas_plink, but I always have the same problem. 
```
----> 1 from pandas_plink import read_plink1_bin

ImportError: cannot import name 'read_plink1_bin' from 'pandas_plink' (/home/username/anaconda3/lib/python3.7/site-packages/pandas_plink/__init__.py)
```

I tried to update and reinstall Anaconda, but It didn't help. 
What I should do? 
The function "read_plink" works, but I do not understand completely how to use it. 

Thanks in advance.

**Comment by horta** [comment]
Is it version 2.0.0? `pandas_plink.__version__`
Btw, I just pushed pandas-plink 2 to conda-forge. It should be available in a couple of minutes.
