### ISSUE TITLE
Reading Data to Xarray Taking a long Time

### ISSUE THREAD

**Issue by robloughnan** [limix/pandas-plink#12]
Hi, 

I am trying to read in a subsample of UKBiobank data (1000 individuals) at ~500,000 SNPS that are across all chromosomes and its taking a long time. I am trying to read this directly into a xarray 

`X = G[indiv,SNPs].compute()`

where `indiv` and `SNPs` are binary vectors. I'm working on a server that I believe has enough memory (256Gb) to hold this directly in memory. It is taking a very long amount of time (hours) to read this in. Could this have anything to with the chunksize and is there any chunksize you would recommend? Is there anything you would recommend for speeding this up?

Thanks in advance for you help, this package has been very useful for me.

**Comment by horta** [comment]
Hi @robloughnan , are your binary vectors more or less randomly distributed? If so, doing  `G[indiv,SNPs].compute()` will effectively result in reading the whole file. 

Try to postpone the `compute()` call. For example, if you want to compute `X  @ X.T`, do instead:

```python
X = G[indiv,SNPs]
K = (X @ X.T).compute()
```

The point of using Xarray is to allow it to decide which bits of the matrix it needs to load at what time according to the matricial operations you need.

If postponing `compute()` call still doesn't solve your problem, try to slice that `G` matrix according to the matricial operations you need. For example, you could loop over SNPs:

```python
K = np.zeros((n_indivs, n_indivs))
for snp_index in SNP_indices:
    g = X[indiv, [snp_index]]
    K += (g @ g.T).compute()
```

Here is a very efficient way to  perform that kind of matrix multiplication when we know that `G` is lazy loaded matrix: https://github.com/limix/limix/blob/ebcd261a95ae7e0a3ecb7f17b7d379cc4140b328/limix/stats/_kinship.py#L4
