### ISSUE TITLE
Saving dataframe as plink?

### ISSUE THREAD

**Issue by loftusa** [limix/pandas-plink#14]
Any plans to include output as well as input functionality?

**Comment by horta** [comment]
Would that be very useful for many people? I would implement that only if that is the case...

**Comment by koelling** [comment]
Yes, this would be useful for me too!

**Comment by horta** [comment]
Will try to implement it tomorrow.

**Comment by horta** [comment]
Implemented: https://pandas-plink.readthedocs.io/en/latest/api/pandas_plink.write_plink1_bin.html
It will be released in a moment (as version 2.2.0).
