### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by duzc19940423** [limix/pandas-plink#20]
Hi, 
the following code generate the error "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"
`G = read_plink1_bin("./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.bed", 
                    "./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.bim", 
                    "./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.fam", verbose=True)`

the input files were generated by `PLINK v1.90b6.20`,  the detailed error message is
`
ValueError                                Traceback (most recent call last)
<ipython-input-11-91a828a7f0bf> in <module>
----> 1 G = read_plink1_bin("./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.bed", "./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.bim", "./3.filtering_samples_and_SNPs/prov_sample.indF3_mds_pca.fam")

~/software/miniconda3/lib/python3.7/site-packages/pandas_plink/_read.py in read_plink1_bin(bed, bim, fam, verbose, ref, chunk)
    255     nsamples = fam_df.shape[0]
    256     sample_ids = fam_df["iid"]
--> 257     variant_ids = bim_df["chrom"] + "_" + bim_df["snp"]
    258 
    259     if ref == "a1":

~/software/miniconda3/lib/python3.7/site-packages/pandas/core/ops/common.py in new_method(self, other)
     62 
     63         other = item_from_zerodim(other)
---> 64 
     65         return method(self, other)
     66 

~/software/miniconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py in wrapper(left, right)
    501     elif is_list_like(right) and not isinstance(right, (ABCSeries, ABCDataFrame)):
    502         # GH17901
--> 503         right = to_series(right)
    504 
    505     if flex is not None and isinstance(right, ABCDataFrame):

~/software/miniconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in arithmetic_op(left, right, op, str_rep)
    195 def comparison_op(left: ArrayLike, right: Any, op) -> ArrayLike:
    196     """
--> 197     Evaluate a comparison operation `=`, `!=`, `>=`, `>`, `<=`, or `<`.
    198 
    199     Parameters

~/software/miniconda3/lib/python3.7/site-packages/pandas/core/ops/array_ops.py in na_arithmetic_op(left, right, op, str_rep)
    147             #  In this case we do not fall back to the masked op, as that
    148             #  will handle complex numbers incorrectly, see GH#32047
--> 149             raise
    150         result = masked_arith_op(left, right, op)
    151 

~/software/miniconda3/lib/python3.7/site-packages/pandas/core/computation/expressions.py in evaluate(op, a, b, use_numexpr)
    229     op_str = _op_str_mapping[op]
    230     if op_str is not None:
--> 231         use_numexpr = use_numexpr and _bool_arith_check(op_str, a, b)
    232         if use_numexpr:
    233             return _evaluate(op, op_str, a, b)  # type: ignore

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

looking forward to your help.
Thank you.

**Comment by horta** [comment]
Hi, I have just released the version 2.2.2 to fix it. Let me know if if doesn't...
