### ISSUE TITLE
Slower performance of read_plink1_bin vs read_plink

### ISSUE THREAD

**Issue by francois-a** [limix/pandas-plink#21]
Hi,

I've only compared version 2.2.2 (after upgrading from 2.0.5), but am getting significantly slower load times with the new function: 
```python
from pandas_plink import read_plink
bim, fam, bed = read_plink(plink_prefix_path, verbose=True)
```
takes ~25 s for a VCF with ~11M variants and ~850 samples, whereas
```python
from pandas_plink import read_plink1_bin
G = read_plink1_bin(plink_prefix_path+'.bed', verbose=True)
```
takes ~7.5 min on the same VCF. The interface of `read_plink` is very convenient -- why is this being deprecated?

**Comment by horta** [comment]
Hi @francois-a ,

Can I have access to your files so I can test it here?

I thought about deprecating `read_plink` because It sounded to be that `read_plink1_bin` returned value was more intuitive. Do you prefer `big, fam, bed` over `G`? (I can revert that deprecation.)

**Comment by francois-a** [comment]
I personally find the old interface much more convenient to work with, so would prefer if that weren't deprecated.

I can't share the original data to replicate the issue, but generated some random data that replicates the behavior [here](https://personal.broadinstitute.org/francois/pandas_plink_read_test.tar).

I'm getting the following timings:
```python
bed, bim, fam = read_plink('pandas_plink_read_test')
```
takes ~800 ms, whereas
```python
G = read_plink1_bin('pandas_plink_read_test.bed')
```
takes ~20 s.

Thanks!

**Comment by horta** [comment]
I have removed the deprecation from that function (and improved its documentation).

I've downloaded your example. I will debug it later this week. Thanks a lot!
