### ISSUE TITLE
❓ `np.nan` value from bed.compute()

### ISSUE THREAD

**Issue by SamuelCahyawijaya** [limix/pandas-plink#22]
Hi, 

I try to follow `1000G_example.ipynb` with `read_plink` function and when I compute the genotype code from bed file, I get some `nan` values, does this value represents binary genotype code `3` which is Homozygous for second allele?

Thank you

**Comment by horta** [comment]
Hi @SamuelCahyawijaya ,

I've just update it (now it is named `Example.ipynb`). Please, have another look at it.

`NaN` means missing value. Please, have a look at https://pandas-plink.readthedocs.io/en/latest/api/pandas_plink.read_plink.html I have just added an example there.

Thank you for the interest =)

**Comment by SamuelCahyawijaya** [comment]
Hi @horta ,

Thanks for your help and quick response 👍 
I have checked the documentation and the updated `Example.ipynb`, it is clear now.

Thank you :)
