### ISSUE TITLE
Hi Danilo, question about writing Plink file from GEO SNP-Chip data

### ISSUE THREAD

**Issue by CholoTook** [limix/pandas-plink#23]
Hi Danilo,

You remember the good old days playing table football in the canteen at EBI?

Fun times!

I noticed that you wrote https://pypi.org/project/pandas-plink/ ?

I want to create bed, bim, fam from SNP-Chip data in GEO.

I'm reading in data using GeoParse, which gives me a pandas dataframe. Seems like it should be a simple step to then write that out in Plink format using pandas-plink?

Any tips?

Many thanks,
Dan.

**Comment by CholoTook** [comment]
I think all I need is a 'real' example of G here:
https://pandas-plink.readthedocs.io/en/latest/api/pandas_plink.write_plink1_bin.html

You use a 'dummy' G with no samples and no genotypes.

**Comment by horta** [comment]
Hi Dan, of course I remember =) I want to play again when this pandemic is over.

I'm going to do some refactoring for this package because there is also some slowness. And thanks for the pull request!

**Comment by CholoTook** [comment]
Awesome!

I'm afraid I didn't actually test the doctest... I'm not sure exactly what I would need to do to do that.

If you can show me how to run the doctest tests, I can fix any failures due to my guessing.

Here is an example of me using your code 'in anger':
https://gist.github.com/CholoTook/60968e3ab6d90cb8fd19be55a25592f1


Cheers,
Dan.

**Comment by CholoTook** [comment]
P.S. Just let me know when... Team Smash will have a come back tour ;-P

**Comment by horta** [comment]
=P

I've just released 2.2.5. It should load files much faster as well.
