### ISSUE TITLE
Hangs on bed.compute()

### ISSUE THREAD

**Issue by jvierstra** [limix/pandas-plink#25]
Transforming the dask object to Pandas w/ the .compute() function hangs for a long period of time.

I have a BED matrix of 22M variants x 300 samples and selecting 1 row:

bed[0,:].compute()

takes ~10 mins.

Using Python 3.6.4

**Comment by jvierstra** [comment]
Looks like there is an issue w/ Python 3.6. I changed to 3.8 and it works. You Might want to change setup.cfg to require at least 3.8.

**Comment by horta** [comment]
Thank you! I'm requiring python 3.7 now.
