### ISSUE TITLE
Install 2.2.9 using pip?

### ISSUE THREAD

**Issue by CholoTook** [limix/pandas-plink#26]
Sorry for being newb, but how do I get 2.2.9 using pip?

I've set up a virtualenv, and then typed `pip install pandas-plink>=2.2.9`, but when I look at `.venv/lib/python3.6/site-packages/pandas_plink/__init__.py`, I see `__version__ = "2.2.4"`.

I'm asking because I'm seeing this error:
```
Traceback (most recent call last):
  File "convert_to_plink.py", line 5, in <module>
    import pandas_plink
  File ".venv/lib/python3.6/site-packages/pandas_plink/__init__.py", line 1, in <module>
    from ._chunk import Chunk
  File ".venv/lib/python3.6/site-packages/pandas_plink/_chunk.py", line 1, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by horta** [comment]
You can try `which pip` to make sure pip is coming from that venv.

You can always do `pip install pandas-plink --upgrade` as well.

**Comment by CholoTook** [comment]
Not working for me:

https://asciinema.org/a/HbiGc32mhjJIo2Pm29wV9X4f1

**Comment by horta** [comment]
We dropped suuport for python 3.6, sorry... Please, update to python 3.7 at least and that will work again..

**Comment by CholoTook** [comment]
Ah, no problem. Can this not be set in the pip deps?

**Comment by horta** [comment]
Not on pip but on setuptools: https://github.com/limix/pandas-plink/blob/b580df7f8d3c566f6cdf8da512c608fd76ff1f0c/setup.cfg#L29
