### ISSUE TITLE
Increase of memory

### ISSUE THREAD

**Issue by FBoyang** [limix/pandas-plink#27]
Dear Developers:

I notice that after the last pandas-plink update, the memory needed to load the same amount of matrix significantly increase (during the process of lazy loading). I wonder could you resolve this issue

**Comment by changebio** [comment]
I met the same issue. When I tried to read chr1 plink file, I gave 60G and failed. but I increased to 128G and it worked
<img width="1202" alt="Screen Shot 2021-11-22 at 2 58 58 PM" src="https://user-images.githubusercontent.com/10182773/142927010-011e0cba-9076-4c7f-8f8a-cf8be38c2fe2.png">
.

**Comment by horta** [comment]
I will close it as it seems to be solved. Sorry for picking it up just now...
