### ISSUE TITLE
support for int8

### ISSUE THREAD

**Issue by rborder** [limix/pandas-plink#30]
I'd like to read in plink data to `int8` arrays rather than `float32`. Looking at  `_bed_read.py` it seems this could be done at the chunk level by modifying `_read_bed_chunk()`. Are their any gotchas I'm missing? Happy to contribute this feature

**Comment by dbolser** [comment]
Are the tests sufficient to assure you that you're catching all gotchas?

**Comment by horta** [comment]
I considered that before but I chose to support only one type for simplicity. Is there a very good reason to support other types?

**Comment by dbolser** [comment]
I assume to reduce memory footprint of very large genotyping sets. e.g.
clustering on a GPU, etc.

**Comment by horta** [comment]
I guess I will just wait for now... there is this missing value that float32 handles nicely with `nan` as @shz9 mentioned. I will close it for now.
