### ISSUE TITLE
pandas_plink is slow since Dask 2024.2

### ISSUE THREAD

**Issue by bgorissen** [limix/pandas-plink#35]
Dask 2024.2 makes pandas-plink unusably slow (~4 hrs to read a 850 MB bed file). Due to [improved tokenization](https://docs.dask.org/en/stable/changelog.html#v2024-2-0), Dask now computes a sha1 hash of `buff` for each [call to _delayed](https://github.com/limix/pandas-plink/blob/main/pandas_plink/_bed_read.py#L34). Since `buff` has the same size as the file, this takes about a second each time, and this is done approximately 10<sup>4</sup> times. The easiest workaround seems to be setting the [parameter `pure`](https://docs.dask.org/en/latest/_modules/dask/delayed.html#delayed) to False.

**Comment by jan-engelmann** [comment]
Same problem.
`pip install "dask<2024.2" distributed dask-expr --upgrade` solves it for me

**Comment by horta** [comment]
Thank you for the feedback (and sorry for the slow reponse)!

I'm working on that. It should be released with that fix in the next hours!

**Comment by jan-engelmann** [comment]
not solved for me unfortunately. Installing the latest version with pip still freezes when not downgrading dask distributed
