### ISSUE TITLE
ImportError: No module named 'pandas_plink.bed_reader'

### ISSUE THREAD

**Issue by Xparx** [limix/pandas-plink#4]
As the title says, when I try to import pandas_plink it fails on bed_reader.
I'm on 

    python 3.5.2
    pandas-plink (1.2.15)

the complete error message is as follows

```
$ python -c "import pandas_plink; pandas_plink.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.virtualenvs/default/lib/python3.5/site-packages/pandas_plink/__init__.py", line 6, in <module>
    from .read import read_plink
  File "/home/user/.virtualenvs/default/lib/python3.5/site-packages/pandas_plink/read.py", line 10, in <module>
    from .bed_read import read_bed
  File "/home/user/.virtualenvs/default/lib/python3.5/site-packages/pandas_plink/bed_read.py", line 3, in <module>
    from .bed_reader import ffi, lib
ImportError: No module named 'pandas_plink.bed_reader'
```

I use pip install for this package
I have a working version for version 1.1.6.

**Comment by Horta** [comment]
I suspect that it did not install fully: meaning it failed to compile some C code.

Installing from a new environment: pip install pandas-plink
What does it say?

If it looks fine, would you mind listing the files at /home/user/.virtualenvs/default/lib/python3.5/site-packages/pandas_plink/ folder?

**Comment by Xparx** [comment]
I created a new test environment

   mkvirtualenv testing_pandas_plink --python=python3

install ipython for convenience and pandas_plink

    pip install ipython
    pip install pandas-plink

unfortunately the same issue arise.
The content of the directory is as follows.
```
~/.virtualenvs/testing_pandas_plink/lib/python3.5/site-packages/pandas_plink$ ls -R
__pycache__  test  _bed_reader.c  bed_read.py  builder.py  __init__.py  read.py  _test.py

./__pycache__:
bed_read.cpython-35.pyc  __init__.cpython-35.pyc  _test.cpython-35.pyc
builder.cpython-35.pyc   read.cpython-35.pyc

./test:
data_files

./test/data_files:
data.bed  data.bim  data.fam
```

If I interpret this correctly I shoyld have a compiled _bed_reader.something file here as well? 
Let me know if I can do something more.

**Comment by Horta** [comment]
Thanks for the feedback =)
I think I managed to find the solution. A quick workaround is to first install cffi: pip install cffi
and then install pandas-plink normally...

I'm preparing a release that will fix that though...

**Comment by Horta** [comment]
pandas-plink version 1.2.16 will soon be released in an hour or so. That one should fix that issue.  Thanks for reporting the problem =)

**Comment by Xparx** [comment]
Looks good! Thanks for the quick fix.
