### ISSUE TITLE
Support for additional dtypes?

### ISSUE THREAD

**Issue by francois-a** [limix/pandas-plink#9]
Thanks for developing this package!

Is there a specific reason for the hard-coded int64 type? It would be great to have some flexibility here, for example to load imputed dosages as float32, or genotypes as int8 with missing values set to -1.

**Comment by horta** [comment]
Hi @francois-a 
There is not a very good reason, no. I guess you can just do `bed = bed.astype("float32")` after you have read it.

**Comment by francois-a** [comment]
Never mind -- I had overlooked that the plink bed format only encodes genotypes (no dosages). Thanks again for developing this.
